services:
  web:
    image: node:22-slim
    command: "/bin/sh /app/docker/web/entrypoint.sh"
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db-data: